### ISSUE TITLE
Add semicolon no longer functions

### ISSUE THREAD

**Issue by sublimino** [andresdominguez/jsToolbox#12]
The "add semicolon" keyboard shortcut does't work (Debian testing, Idea 15.0.3) and can no longer be remapped as it doesn't appear in the keymap list:

![jstoolbox](https://cloud.githubusercontent.com/assets/134117/12555682/36b36d92-c37a-11e5-9654-669cd17d501d.png)

**Comment by andresdominguez** [comment]
Hello @sublimino 

I removed it because it is not necessary. Use Ctrl SHIFT ENTER to add the ; at the end of the line.

**Comment by sublimino** [comment]
The plugin install docs in intellij still list it as a shortcut FWIW (and I prefer the re-mappable shortcut, but I'll get used to it). Thanks for the update.
